version: '3.8'

services:

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: meu-backend
    ports:
      - "5000:5000"
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/app/utils/asserts:/app/app/utils/asserts:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000}
    container_name: meu-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
