"""Criacaodados

Revision ID: 0cdf22a0542d
Revises: 
Create Date: 2025-04-03 12:44:56.973134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdf22a0542d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imoveis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imoveis',
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('anunciante', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('oferta', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('area_util', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('preco', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('valor_m2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('quartos', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('vagas', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
