"""Criacaodados

Revision ID: a57c135e70d8
Revises: 0cdf22a0542d
Create Date: 2025-04-04 15:47:40.080817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57c135e70d8'
down_revision = '0cdf22a0542d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imoveis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imoveis',
    sa.Column('codigo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('anunciante', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oferta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area_util', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('valor_m2', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quartos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vagas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
