"""Add contratos (wide, mirrors Vendas sheet) and divisao_comissao tables.

Revision ID: 20260624_contratos_domain
Revises: 20260624_visitas_domain
Create Date: 2026-06-24
"""

from alembic import op
import sqlalchemy as sa


revision = "20260624_contratos_domain"
down_revision = "20260624_visitas_domain"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "contratos",
        sa.Column("id_contrato", sa.String(length=50), nullable=False),
        sa.Column('data_contrato', sa.Date(), nullable=True),
        sa.Column('contrato', sa.Text(), nullable=True),
        sa.Column('valor_negocio', sa.Numeric(14, 2), nullable=True),
        sa.Column('valor_comissao', sa.Numeric(14, 2), nullable=True),
        sa.Column('valor_total_61', sa.Numeric(14, 2), nullable=True),
        sa.Column('nf_61_imoveis', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_gerente_venda', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_gerente_captacao', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_diretor', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_corretor_venda_1', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_corretor_captacao_1', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_corretor_venda_2', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_corretor_captacao_2', sa.Numeric(14, 2), nullable=True),
        sa.Column('valor_gerente_venda', sa.Numeric(14, 2), nullable=True),
        sa.Column('gerente_venda_nome', sa.Text(), nullable=True),
        sa.Column('valor_gerente_captacao', sa.Numeric(14, 2), nullable=True),
        sa.Column('gerente_captacao_nome', sa.Text(), nullable=True),
        sa.Column('valor_diretor', sa.Numeric(14, 2), nullable=True),
        sa.Column('diretor_nome', sa.Text(), nullable=True),
        sa.Column('valor_corretor_venda_1', sa.Numeric(14, 2), nullable=True),
        sa.Column('corretor_venda_1_nome', sa.Text(), nullable=True),
        sa.Column('valor_corretor_venda_2', sa.Numeric(14, 2), nullable=True),
        sa.Column('corretor_venda_2_nome', sa.Text(), nullable=True),
        sa.Column('valor_corretor_captador_1', sa.Numeric(14, 2), nullable=True),
        sa.Column('corretor_captador_1_nome', sa.Text(), nullable=True),
        sa.Column('valor_corretor_captador_2', sa.Numeric(14, 2), nullable=True),
        sa.Column('corretor_captador_2_nome', sa.Text(), nullable=True),
        sa.Column('data_assinatura', sa.Date(), nullable=True),
        sa.Column('data_escritura', sa.Date(), nullable=True),
        sa.Column('data_quitacao', sa.Date(), nullable=True),
        sa.Column('data_posse', sa.Date(), nullable=True),
        sa.Column('parcelas_comissao', sa.Text(), nullable=True),
        sa.Column('data_parcela1_comissao', sa.Date(), nullable=True),
        sa.Column('correspondente_bancario', sa.Text(), nullable=True),
        sa.Column('data_envio_docs_financ', sa.Date(), nullable=True),
        sa.Column('data_vistoria', sa.Date(), nullable=True),
        sa.Column('num_protocolo_1', sa.Text(), nullable=True),
        sa.Column('num_protocolo_2', sa.Text(), nullable=True),
        sa.Column('num_protocolo_3', sa.Text(), nullable=True),
        sa.Column('num_protocolo_4', sa.Text(), nullable=True),
        sa.Column('descricao_trello', sa.Text(), nullable=True),
        sa.Column('anexo_contrato', sa.Text(), nullable=True),
        sa.Column('anexo_docs_pessoais_compradores', sa.Text(), nullable=True),
        sa.Column('anexo_docs_pessoais_vendedores', sa.Text(), nullable=True),
        sa.Column('anexo_onus', sa.Text(), nullable=True),
        sa.Column('anexo_cert_negativas_vendedores', sa.Text(), nullable=True),
        sa.Column('anexo_cert_negativa_imovel', sa.Text(), nullable=True),
        sa.Column('anexo_ficha_cadastral', sa.Text(), nullable=True),
        sa.Column('nome_comprador1', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador1', sa.Text(), nullable=True),
        sa.Column('nome_comprador2', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador2', sa.Text(), nullable=True),
        sa.Column('finciamento', sa.Text(), nullable=True),
        sa.Column('imobiliaria_venda', sa.Text(), nullable=True),
        sa.Column('imobiliaria_cap', sa.Text(), nullable=True),
        sa.Column('liquido_61', sa.Numeric(14, 2), nullable=True),
        sa.Column('neg_gerado_v1', sa.Numeric(14, 2), nullable=True),
        sa.Column('neg_gerado_v2', sa.Numeric(14, 2), nullable=True),
        sa.Column('neg_gerado_c1', sa.Numeric(14, 2), nullable=True),
        sa.Column('neg_gerado_c2', sa.Numeric(14, 2), nullable=True),
        sa.Column('vgv_v1', sa.Numeric(14, 2), nullable=True),
        sa.Column('vgv_v2', sa.Numeric(14, 2), nullable=True),
        sa.Column('vgv_c1', sa.Numeric(14, 2), nullable=True),
        sa.Column('vgv_c2', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_comissao_61', sa.Numeric(14, 2), nullable=True),
        sa.Column('nome_vendedor1', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor1', sa.Text(), nullable=True),
        sa.Column('nome_vendedor2', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor2', sa.Text(), nullable=True),
        sa.Column('valor_parcela_comissao_1', sa.Numeric(14, 2), nullable=True),
        sa.Column('data_parcela2_comissao', sa.Date(), nullable=True),
        sa.Column('data_parcela3_comissao', sa.Date(), nullable=True),
        sa.Column('nome_vendedor3', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor3', sa.Text(), nullable=True),
        sa.Column('nome_vendedor4', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor4', sa.Text(), nullable=True),
        sa.Column('nome_vendedor5', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor5', sa.Text(), nullable=True),
        sa.Column('nome_comprador3', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador3', sa.Text(), nullable=True),
        sa.Column('nome_comprador4', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador4', sa.Text(), nullable=True),
        sa.Column('nome_comprador5', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador5', sa.Text(), nullable=True),
        sa.Column('nome_comprador6', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador6', sa.Text(), nullable=True),
        sa.Column('nome_comprador7', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador7', sa.Text(), nullable=True),
        sa.Column('nome_comprador8', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador8', sa.Text(), nullable=True),
        sa.Column('valor_parcela_comissao_2', sa.Numeric(14, 2), nullable=True),
        sa.Column('valor_parcela_comissao_3', sa.Numeric(14, 2), nullable=True),
        sa.Column('data_parcela4_comissao', sa.Date(), nullable=True),
        sa.Column('valor_parcela_comissao_4', sa.Numeric(14, 2), nullable=True),
        sa.Column('data_parcela5_comissao', sa.Date(), nullable=True),
        sa.Column('valor_parcela_comissao_5', sa.Numeric(14, 2), nullable=True),
        sa.Column('origem_lead', sa.Text(), nullable=True),
        sa.Column('bairro', sa.Text(), nullable=True),
        sa.Column('tipo', sa.Text(), nullable=True),
        sa.Column('nome_comprador9', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador9', sa.Text(), nullable=True),
        sa.Column('nome_comprador10', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador10', sa.Text(), nullable=True),
        sa.Column('nome_comprador11', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador11', sa.Text(), nullable=True),
        sa.Column('nome_comprador12', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador12', sa.Text(), nullable=True),
        sa.Column('nome_comprador13', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador13', sa.Text(), nullable=True),
        sa.Column('nome_comprador14', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador14', sa.Text(), nullable=True),
        sa.Column('nome_comprador15', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_comprador15', sa.Text(), nullable=True),
        sa.Column('nome_vendedor6', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor6', sa.Text(), nullable=True),
        sa.Column('nome_vendedor7', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor7', sa.Text(), nullable=True),
        sa.Column('nome_vendedor8', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor8', sa.Text(), nullable=True),
        sa.Column('nome_vendedor9', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor9', sa.Text(), nullable=True),
        sa.Column('nome_vendedor10', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor10', sa.Text(), nullable=True),
        sa.Column('nome_vendedor11', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor11', sa.Text(), nullable=True),
        sa.Column('nome_vendedor12', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor12', sa.Text(), nullable=True),
        sa.Column('nome_vendedor13', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor13', sa.Text(), nullable=True),
        sa.Column('nome_vendedor14', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor14', sa.Text(), nullable=True),
        sa.Column('nome_vendedor15', sa.Text(), nullable=True),
        sa.Column('email_telefone_cpf_vendedor15', sa.Text(), nullable=True),
        sa.Column('percentual_premiacao_jose', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_premiacao_marcelo', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_premiacao_luana', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_premiacao_thais', sa.Numeric(14, 2), nullable=True),
        sa.Column('percentual_premiacao_diretor', sa.Numeric(14, 2), nullable=True),
        sa.Column('check_box_gvenda', sa.Text(), nullable=True),
        sa.Column('check_box_gcap', sa.Text(), nullable=True),
        sa.Column('check_box_diretor', sa.Text(), nullable=True),
        sa.Column('codigo_imovel', sa.Text(), nullable=True),
        sa.Column('data_pagamento_sinal', sa.Date(), nullable=True),
        sa.Column('data_parcela_intermediaria', sa.Date(), nullable=True),
        sa.Column('link_honorario', sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint("id_contrato"),
    )

    op.create_table(
        "divisao_comissao",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_contrato", sa.String(length=50), nullable=True),
        sa.Column("papel", sa.String(length=50), nullable=True),
        sa.Column("id_corretor", sa.String(length=50), nullable=True),
        sa.Column("nome_corretor", sa.Text(), nullable=True),
        sa.Column("percentual", sa.Numeric(14, 4), nullable=True),
        sa.Column("comissao_valor", sa.Numeric(14, 2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_divisao_comissao_id_contrato", "divisao_comissao", ["id_contrato"])
    op.create_index("ix_contratos_data_contrato", "contratos", ["data_contrato"])


def downgrade():
    op.drop_table("divisao_comissao")
    op.drop_table("contratos")
